### ISSUE TITLE
ERROR in ./src/vendor.ts ERROR in ./src/main.ts

### ISSUE THREAD

**Issue by aaroncalderon** [magarcia/generator-angular2-webpack-starter#7]
Hi, Any thoughts on this one?

When I run this...

`npm run server`

I get...

```
ERROR in ./src/vendor.ts
Module build failed: Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (C:\dev\p\apollostack\yo-ng2-webpack\node_modules\tslint\lib\ruleLoader.js:29:15)
    at Linter.lint (C:\dev\p\apollostack\yo-ng2-webpack\node_modules\tslint\lib\tslint.js:25:44)
    at Object.lint (C:\dev\p\apollostack\yo-ng2-webpack\node_modules\tslint-loader\index.js:64:23)
    at Object.module.exports (C:\dev\p\apollostack\yo-ng2-webpack\node_modules\tslint-loader\index.js:126:8)

ERROR in ./src/main.ts
Module build failed: Error: Could not find the following rules specified in the configuration:
no-trailing-comma
    at Object.loadRules (C:\dev\p\apollostack\yo-ng2-webpack\node_modules\tslint\lib\ruleLoader.js:29:15)
    at Linter.lint (C:\dev\p\apollostack\yo-ng2-webpack\node_modules\tslint\lib\tslint.js:25:44)
    at Object.lint (C:\dev\p\apollostack\yo-ng2-webpack\node_modules\tslint-loader\index.js:64:23)
    at Object.module.exports (C:\dev\p\apollostack\yo-ng2-webpack\node_modules\tslint-loader\index.js:126:8)
webpack: bundle is now VALID.
```
# UPDATE

I commented out line [tslint.json#L23](https://github.com/magarcia/generator-angular2-webpack-starter/blob/master/app/templates/tslint.json#L23) and it went through. However, I think that we need to update the the version of tslint to @3.9.0 (**maybe**).

**Comment by vikrambarnwal** [comment]
Same Error Please help me out
